# Generated by Django 4.1.1 on 2022-09-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('ops1', models.CharField(max_length=255)),
                ('ops2', models.CharField(max_length=255)),
                ('ops3', models.CharField(max_length=255)),
                ('ans', models.CharField(max_length=255)),
            ],
        ),
    ]
