# Generated by Django 4.1.1 on 2022-09-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ops4',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
